# Generated by Django 3.0.6 on 2020-06-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QutoesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qutoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('qutoes', models.TextField()),
                ('qutoes_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qutoes.QutoesCategory')),
            ],
        ),
    ]
